# -*- coding: utf-8 -*-
"""market basket .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KM1TTugVDQaPafTHSY76aPZtpypmvymm
"""

import warnings
warnings.simplefilter("ignore", DeprecationWarning)

import warnings

warnings.simplefilter("ignore", DeprecationWarning)
warnings.filterwarnings("ignore", category=DeprecationWarning)

import warnings

warnings.filterwarnings(
    "ignore",
    message=".*datetime.datetime.utcnow.*",
    category=DeprecationWarning
)

!pip install scikit-learn==1.9.0

import sklearn
print(sklearn.__version__)

!pip install mlxtend openpyxl

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

# Load the dataset
df = pd.read_csv("Online Retail.csv")

# Display the first 5 rows
df.head()

df.shape

df.info()

df.describe()

df.isnull().sum()

df = df.dropna()

df = df[~df['InvoiceNo'].astype(str).str.contains('C')]

df = df[df['Quantity'] > 0]

df = df[['InvoiceNo','Description','Quantity']]

df.head()

basket = (df
          .groupby(['InvoiceNo','Description'])['Quantity']
          .sum()
          .unstack()
          .fillna(0))

print(basket.shape)

basket_small = basket.head(5000)

basket_small = basket_small.apply(lambda x: x > 0)

basket = basket.applymap(lambda x: 1 if x > 0 else 0)

basket.head()

frequent_itemsets = apriori(
    basket_small,
    min_support=0.02,
    use_colnames=True,
    low_memory=True
)

frequent_itemsets.head()

print(frequent_itemsets.shape)
frequent_itemsets.head(10)

frequent_itemsets.sort_values(
    by="support",
    ascending=False
)

rules = association_rules(
    frequent_itemsets,
    metric="confidence",
    min_threshold=0.5
)

rules.head()

rules = rules[['antecedents',
               'consequents',
               'support',
               'confidence',
               'lift']]

rules.head(20)

rules.sort_values(
    by='lift',
    ascending=False
)

rules.to_csv(
    "association_rules.csv",
    index=False
)

top10 = frequent_itemsets.sort_values(
    by='support',
    ascending=False
).head(10)

plt.figure(figsize=(12,6))

plt.bar(
    range(len(top10)),
    top10['support']
)

plt.xticks(
    range(len(top10)),
    [', '.join(list(x)) for x in top10['itemsets']],
    rotation=90
)

plt.title("Top 10 Frequent Itemsets")

plt.xlabel("Itemsets")

plt.ylabel("Support")

plt.show()

plt.figure(figsize=(8,6))

plt.scatter(
    rules['confidence'],
    rules['lift']
)

plt.xlabel("Confidence")

plt.ylabel("Lift")

plt.title("Confidence vs Lift")

plt.show()

print(rules.shape)
rules.head()

print(frequent_itemsets.shape)
frequent_itemsets.head()

print("Total Transactions :", basket.shape[0])

print("Unique Products :", basket.shape[1])

print("Frequent Itemsets :", len(frequent_itemsets))

print("Association Rules :", len(rules))